# Generated by Django 2.1a1 on 2018-05-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotUser')),
            ],
        ),
        migrations.CreateModel(
            name='MxmTrack',
            fields=[
                ('commontrack_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('track_name', models.TextField()),
                ('artist_name', models.TextField()),
                ('album_id', models.PositiveIntegerField()),
                ('artist_id', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='botuser',
            name='favorites',
            field=models.ManyToManyField(to='bot.MxmTrack'),
        ),
    ]
