# Generated by Django 2.1a1 on 2018-05-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxmtrack',
            name='track_url',
            field=models.URLField(default='https://www.musixmatch.com/'),
        ),
    ]
