# Generated by Django 2.1a1 on 2018-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20180525_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mxmtrack',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mxmtrack',
            name='spotify_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
