# Generated by Django 2.1a1 on 2018-05-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20180525_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxmtrack',
            name='vanity_id',
            field=models.TextField(default='Track name'),
            preserve_default=False,
        ),
    ]
