# Generated by Django 2.1a1 on 2018-05-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_mxmtrack_vanity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxmtrack',
            name='album_name',
            field=models.TextField(default='album'),
            preserve_default=False,
        ),
    ]
