# Generated by Django 2.1a1 on 2018-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20180526_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageevent',
            name='type',
            field=models.CharField(choices=[('LY', 'Lyrics'), ('CO', 'Command'), ('FA', 'Favorite')], default='LY', max_length=2),
        ),
    ]
